x-postgres-env: &postgres-env
  POSTGRES_HOST: db
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: fastapi_development

services:
  db:
    image: postgres:17.4
    environment:
      <<: *postgres-env
      POSTGRES_HOST_AUTH_METHOD: "trust\nhost postgres all 0.0.0.0/0 md5"
      POSTGRES_INITDB_ARGS: "--auth-host=trust"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *postgres-env
    ports:
      - "3000:3000"
    depends_on:
      - db

  haproxy:
    image: haproxy:latest
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./errors/:/usr/local/etc/haproxy/errors/:ro
    depends_on:
      - app

  seed:
    image: alpine/curl:latest
    depends_on:
      - app
    volumes:
      - ./seed.sh:/seed.sh
    command: sh -c "apk add --no-cache bash jq && chmod +x /seed.sh && /seed.sh"
    environment:
      - API_URL=http://app:3000

volumes:
  pg-data:
